#!/bin/bash

current_user=$(whoami)

if [ $(stat -c %U hello) = "guillaume" ]; then

    chown betty hello
    echo "The owner of hello has been changed to betty."
else
    echo "The file hello is not owned by guillaume."
fi
